name: Continuous Integration (CI)

# Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: bash ./gradlew test
      
      - name: Unit Test Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build sonar --info